project:
  type: website
  output-dir: ../docs

website:
  title: "Modulo"
  google-analytics: "G-4KRLE15B5S"
  navbar:
    right:
      - text: "Home"
        href: index.qmd   # Links to the homepage
      - text: "About"
        href: about.qmd    # Links to the about page
      - text: "Plasma Book"
        href: ../book/index.html #chapters/index.qmd
      - text: "Extratemporal Dimensions"
        href: ../monograph/index.html #chapters/index.qmd
      - text: "Code Notes"
        menu:
          - text: "Python"
            href: code_notes/python-notes.qmd
          - text: "Command Line"
            href: code_notes/bash-notes.qmd
          - text: "Git"
            href: code_notes/git-notes.qmd
          - text: "SQL"
            href: code_notes/sql-notes.qmd
          - text: "Cython"
            href: code_notes/cython-notes.qmd
          - text: "Docker"
            href: code_notes/docker-notes.qmd
          - text: "Rust"
            href: code_notes/rust-notes.qmd 




#format:
#  html:
#    theme: litera
#    css: styles.css


