project:
  type: website
  output-dir: ../docs/blog

website:
  title: "Henry Watkins"
  google-analytics: "G-4KRLE15B5S"
  navbar:
    right:
      - text: "Home"
        href: index.qmd   # Links to the homepage
      - text: "Blog"
        href: blog.qmd    # Links to the blog page
      #- text: "Plasma Book"
      #  href: ../book/index.html #chapters/index.qmd

#format:
#  html:
#    theme: litera
#    css: styles.css


