project:
  type: book
  output-dir: ../docs/book

book:
  title: "Practical Plasma Physics: Lasers, Transport, and Magnetic Effects"
  author: "Henry Watkins"
  chapters:
    - index.qmd
    - mhd.qmd
    - collisions.qmd
    - transport.qmd
    - nonlocal_transport.qmd
    - lasers.qmd
    - laserplasma.qmd
    - applications.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-location: left
  #pdf:
  #  documentclass: scrreprt
  #epub:
  #  cover-image: cover.png



