# Inertial Confinement Fusion {#sec-applications}

With this in mind, what do we use the physics we have covered for? The primary application of plasma physics research is fusion energy devices like magnetic confinement fusion and inertial confinement fusion, the latter of which also incorporates laser physics and the science of laser-plasma interactions. 

The fusion of two nuclei occurs when they collide with the energy to overcome the Coulomb barrier between the particles, allowing the attractive strong nuclear force to bind a set of the constituent nucleons into a more energetically stable daughter product. The rate of this process is significantly increased by quantum tunnelling, whereby the incoming particles can tunnel through the Coulomb barrier, reducing the amount of energy required by each particle. Nuclear fusion in the sun is dominated by two processes, the proton-proton chain reaction and the carbon-nitrogen-oxygen cycle. Unfortunately for physicists, the conditions in the core of the sun where these processes occur are not replicable in laboratories on Earth.

While the processes that power the sun are out of reach, other fusion processes have much higher cross-sections for conditions achievable on Earth. The reaction most amenable to laboratory fusion is the reaction of a deuterium and a tritium nucleus into an $\alpha-$particle and a neutron
$$
    {}_1^2 D + {}_1^3 T \rightarrow {}_2^4 He + n. 
$$
This reaction has a very high cross-section relative to other light nuclei and so is the chosen reaction in all potential fusion schemes. By considering the fusion energy gain versus energy losses in a hypothetical power plant, the requirements for a viable fusion plant is given by the Lawson Criterion. It requires the product of fuel number density $n$ and energy confinement time $\tau$ to be above a critical value,
$$
    n\tau > \frac{12 k_b T}{\langle \sigma v\rangle E_{\alpha}}.
$$
Here $E_{\alpha}$ is the energy of the alpha particle product, $T$ is the fuel temperature and $\langle \sigma v\rangle$ comes from the D-T fusion reaction rate $W=n_t n_d \langle \sigma v\rangle$, with deuterium and tritium number densities $n_d, n_t$, respectively.

Inertial confinement fusion attempts to reach the density and confinement time requirements of the Lawson Criterion by confining a plasma with its own inertia, such that it converges to a central 'hotspot' surrounded by cooler, denser fuel with the density and temperature required for nuclear fusion to occur. This confinement can be performed using several approaches including Z pinches and high-power lasers. Whilst numerous inertial fusion schemes exist, this thesis will remain in the context of direct-drive inertial confinement fusion, indirect-drive inertial confinement fusion and magnetised liner inertial fusion (MagLIF). 

## Inertial Fusion Schemes

In direct-drive inertial confinement fusion a fuel capsule filled with a mixture of deuterium and tritium is illuminated directly by an array of high-power $~10^{15}Wcm^{-2}$ nanosecond laser pulses. The energy is absorbed at the surface of the capsule, ablating material off the surface and forming a plasma corona. In order to conserve momentum, the inner material is compressed by a 'rocket effect', driving the fuel to a high temperature hotspot, surrounded by a cooler, denser region. When the fuel ignites in the centre, the subsequent production of alpha particles spread out, causing a `burn-wave' through the rest of the fuel. In this scheme, lasers propagate directly through the corona, imprinting the laser heating profile onto the surface of the capsule. As such this method is susceptible to hydrodynamic instabilities such as the Rayleigh-Taylor instability, seeded by the non-uniform laser imprint and capsule surface roughness, which mix up the plasma and cause non-uniform compression. This degrades confinement and can lead to high-Z material from the shell mixing deep into the fuel, radiating away energy from the core.

Indirect drive inertial confinement fusion instead has the high-power lasers illuminate the interior of a gold 'hohlraum'. This process creates soft X-rays that drive the compression of the fuel capsule held in the centre of the hohlraum. The benefit of X-ray driven compression over direct-drive is the uniformity of the radiation incident on the capsule surface, reducing the impact of laser-seeded hydrodynamic instabilities. However by using a X-ray bath the energy coupling to the capsule is much lower than direct-drive since the conversion of laser energy to X-rays by the hohlraum is not perfectly efficient, with only a fraction (a conversion efficiency of $\sim 15 \%$ is normal) of the incident laser energy eventually driving the capsule compression. In addition, in this process the laser is propagating through a plasma within the hohlraum, a result of a gas-fill or from the ablation of the hohlraum wall. This means the laser can be further susceptible to laser-plasma interactions (LPIs), focusing and backscatter as the beam enters the hohlraum. 

High-power lasers are not the only way to compress a fuel capsule however. A Z-pinch is a pulse power device that drives a very large current, with the Sandia National Laboratory - based Z accelerator producing peak drive currents of 18MA. When this current is passed through a cylindrical liner, it induces a very strong magnetic field. The magnetic pressure of this field implodes the liner, compressing the fuel within to fusion conditions (via $PdV$ work). This convergence process lies at the heart of the MagLIF scheme. Unlike the laser-driven methods described above, the convergence is cylindrical, with a density that changes with $\sim (R_i/R_f)^2$; by comparison in spherical convergence the density changes as $\sim (R_i/R_f)^3$. To account for this less efficient compression, a pre-heat laser is used to heat the fuel in the capsule, pushing it onto a higher adiabat. This entails laser propagation through a `window' into the fuel, exciting similar laser-plasma interactions and requiring a thorough understanding of thermal transport in the core.

Inertial fusion experiments were initially invented to create burning thermonuclear fuel; however, these experimental setups have also found uses in creating exotic forms of matter such as warm dense matter, studying astrophysical analogues in laboratory astrophysics and testing equations of state. The understanding of the physics of high-energy-density plasmas goes beyond nuclear fusion. 

Given the large and complex nature of these experiments - with a great deal of different physics operating at different time and length scales - theory and numerical simulation is paramount in understanding and designing such experiments. The accurate simulation of high-energy-density physics on the world's largest supercomputers is a rich area of science. With the advent of exascale computing, computational physics methods and the design of codes will only become more important in plasma physics.
