# Introduction

This is a book created from markdown and executable code.

See  for additional discussion of literate programming.


\section{The Kinetic Theory of Plasmas}

A plasma is a statistical ensemble of ions and electrons that undergo long-range interactions via the Lorentz force
\begin{equation}
\textbf{F}=q(\textbf{E}+\textbf{v}\times\textbf{B}),
\end{equation}
for some particle of charge $q$. 

Though the electrostatic force of a single particle has an infinite range, the collective nature of an ensemble of charged particles means any charge imbalance will experience shielding from oppositely - charged particles. Considering the thermal motion of charged particles in the electric potential of a charge imbalance, this effect defines a characteristic length scale over which shielding occurs known as the $\textit{Debye length}$
\begin{equation}
    \lambda_D=\left(\frac{\epsilon_0 k_b T_e}{n_e e^2}\right)^{1/2},
\end{equation}
where the electron number density $n_e$ is in $m^{-3}$ and the electron temperature $T_e$ is expressed in units of Kelvin. Physically the Debye length can be considered the length scale of the screening of bare charges in plasma. Beyond a sphere of radius $\lambda_D$, the Debye sphere, the plasma can be considered quasi-neutral.  

The electric fields of this ensemble self-consistently adapt to the charge environment of the collection of particles. As a result imbalances in charge excite plasma oscillations with a characteristic frequency that act to re-establish quasi-neutrality. This frequency is known as the $\textit{plasma frequency}$
\begin{equation}
    \omega_p=\left(\frac{n_e e^2}{m_e \epsilon_0}\right)^{1/2}.
\end{equation}
The plasma frequency defines a timescale above which the plasma can be considered quasi-neutral.   

These two parameters define the length and timescales above which we can define the collective statistical state called a plasma. The most accurate model to describe this N-particle system would be the Liouville equation under the action of a self-consistent electromagnetic field. However, the requirements to solve a system in $6N$ dimensional phase space is not necessary or possible. Instead this collective behaviour is best described in terms of the $\textit{distribution function}$, $f(\textbf{x},\textbf{v},t)$, which represents the particle density in the 6-dimensional single-particle phase space. The evolution of distribution functions is the subject of kinetic theory. A plasma is described kinetically by the $\textit{Vlasov-Fokker-Planck}$ (VFP) equation
\begin{equation}
\frac{\partial f_\alpha}{\partial t} + \textbf{v}_\alpha\cdot\nabla f_\alpha + \frac{q_\alpha}{m_\alpha}(\textbf{E}+\textbf{v}_\alpha\times \textbf{B})\cdot\nabla_v f_\alpha = \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll}
\end{equation}
for a species $\alpha$. The collision operator on the right-hand-side is the Fokker-Planck operator which will be introduced in section 2.3. There is a VFP equation for each species present in the plasma, and represents the conservation of probability in phase space. The collision term on the right-hand-side takes the form of the Fokker-Planck operator, which determines how the Coulomb collisions between particles in the plasma influence the evolution of the distribution function. Intuitively while one would think the electric fields of every particle should influence the evolution of the plasma, Debye shielding allows the separation of the electromagnetic field into a microscopic, fluctuating component that forms part of the collision term, and macroscopic fields that sit in the left hand side of the VFP equation.  

The most accurate approach would be to start straight from the VFP model of a plasma and solve for the electron and ion distribution functions. However one can start with a simpler hydrodynamic approximation. Very collisional plasmas can be assumed to have a distribution function close to a Maxwell-Boltzmann distribution, which for electrons is
\begin{equation}
    f_m=n_e\left(\frac{1}{2\pi v_{th}^2}\right)^{3/2}\exp{\left(-\frac{v^2}{2 v_{th}^2}\right)},
\end{equation}
with the standard deviation being the thermal speed defined as $v_{th}=\sqrt{k_b T_e/m_e}$. This allows the use of a fluid description which can be derived by considering a small deviation from equilibrium, this fluid model is known as Magneto-Hydrodynamics. 

\section{Magneto-Hydrodynamics}

Deriving Magneto-Hydrodynamics (MHD) from kinetic theory consists of taking moments of the VFP equation. These moments are the macroscopic quantities found from taking averages over the distribution; in particular the conserved quantities or mass, momentum and energy. However in taking successive moments, each moment equation couples to the next. To create a closed system of equations, transport relations must be found that couple to a lower-order moment; in MHD this is achieved with the Fokker-Planck collision term.

\subsection*{Moments of the Vlasov-Fokker-Planck Equation}

For a macroscopic fluid model the equations must describe the relationships between macroscopic quantities. The moments are found by multiplying the distribution function by successive velocity variables $v_i$ and integrating over the whole of velocity space. The first few moments below are number density, fluid velocity, total energy density, heat and enthalpy flux and the stress tensor, respectively
\begin{align}
&n(\textbf{r},t) =\int f(\textbf{r},\textbf{v},t)d^3 v, \\
&\textbf{V}(\textbf{r},t)=\langle\textbf{v}\rangle =\frac{1}{n} \int \textbf{v} f(\textbf{r},\textbf{v},t)d^3 v, \\
&\mathcal{E}(\textbf{r},t)= \frac{1}{2} m n \langle v^2\rangle= \frac{1}{2}m\int v^2 f(\textbf{r},\textbf{v},t)d^3 v, \\
&\textbf{q}(\textbf{r},t)= \frac{1}{2}m n \langle w^2 \textbf{v}\rangle = \frac{1}{2}m \int w^2 \textbf{v} f(\textbf{r},\textbf{v},t)d^3 v, \\
&\sigma_{ij}= m n\langle w_i w_j\rangle = m \int w_i w_j f(\textbf{r},\textbf{v},t)d^3 v,
\end{align}
where $w$ is the `anomalous velocity', the deviation from the mean velocity, $\textbf{w}=\textbf{v}-\textbf{V}$. In general the $n^{th}$ moment of the distribution function is
\begin{equation}
\langle \textbf{v}^n\rangle = \frac{1}{n}\int \textbf{v}^n f(\textbf{r},\textbf{v},t)d^3 v.
\end{equation}

Taking the first moment of the VFP equation for species $\alpha$ yields the continuity equation
\begin{equation}
\frac{\partial n}{\partial t}+\nabla \cdot (n \textbf{V})=\int \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll} d^3v.
\end{equation}
If there are no collisions that lead to a change in particle number of the species in question i.e ionisation or recombination, then
\begin{equation}
\int \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll} d^3v=0.
\end{equation}
The second moment can be found by multiplying the VFP equation by $m\textbf{v}$ and following the same routine to give
\begin{equation}
\frac{\partial}{\partial t}(mn V_j) + \frac{\partial}{\partial x_i}(mn \langle v_i v_j\rangle ) -q n(E_j+(\textbf{V}\times\textbf{B})_j)= \int mv_j \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll} d^3v.
\end{equation}
To put this equation into a more familiar form note that the velocity $\textbf{V}$ is the sum of the average ($\textbf{V}$) and `anomalous' ($\textbf{w}$) parts $\textbf{v}=\textbf{w}+\textbf{V}$, therefore
\begin{align*}
\langle v_i v_j\rangle &= \langle (V_i + w_i)(V_j+w_j)\rangle \\
&= V_iV_j + \langle w_i w_j\rangle, 
\end{align*}
remembering $\langle w_i\rangle=0$ as it is an anomalous, random fluctuation. Putting this into the equation and invoking the continuity equation allows the equation to be written
\begin{equation}
mn\frac{\partial V_i}{\partial t} + mn V_j \frac{\partial V_i}{\partial x_j} - qn(E_i+(\textbf{V}\times\textbf{B})_i)=-\frac{\partial \sigma_{ij}}{\partial x_j}+\int mv_i \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll} d^3v.
\end{equation}
The stress tensor can be written in terms of the isotropic pressure $p$ and anisotropic stress $\pi_{ij}$,
\begin{equation}
\sigma_{ij}=p\delta_{ij}+\pi_{ij}.
\end{equation}

If the plasma is inviscid the anisotropic part is ignored and what is left is the momentum equation,
\begin{equation}
mn\frac{\partial \textbf{V}}{\partial t} + mn \textbf{V}\cdot\nabla \textbf{V} - qn(\textbf{E}+\textbf{V}\times\textbf{B})=-\nabla p+\textbf{R}.
\end{equation}
The collision term has been shortened to
\begin{equation}
\textbf{R}=\int m\textbf{v} \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll}d^3v.
\end{equation}
Which satisfies 
\begin{align*}
    \textbf{R}=\sum_\beta \textbf{R}_{\alpha \beta},
\end{align*}
since there are collisions with all other species. Also note self-collisions conserve momentum, hence $\textbf{R}_{\alpha \alpha}=0$.

The third equation to be derived is the energy equation. However for this thesis the energy equation will be transformed so that the subject is instead temperature. Since Boltzmann's constant $k_b$ is always associated with the temperature $T$, we shall for the remainder of this thesis absorb it into the definition of $T$, which is thereby measured in units of energy rather than degrees (thus $k_b T \rightarrow T$ from here on). Using the following definitions of thermal energy density, kinetic energy density and thermal heat flow,
\begin{align}
&\mathcal{E_T} = \frac{1}{2}mn\langle w^2\rangle = \frac{3}{2}nT, \\
&\mathcal{E}_K = \frac{1}{2}n m V^2, \\
&\textbf{q}'= \frac{1}{2}m n \langle w^2 \textbf{w}\rangle = \frac{1}{2}m \int w^2 \textbf{w} f(\textbf{r},\textbf{v},t)d^3 v,
\end{align}
and the ideal gas law
\begin{equation}
p=nT.
\end{equation}
The temperature equation can be written
\begin{equation}
\frac{3}{2}n\left(\frac{\partial T}{\partial t} + \textbf{V}\cdot\nabla T\right) +\nabla \cdot \textbf{q}'+p\nabla \cdot\textbf{V} =Q,
\end{equation}
where the collision terms have been shortened to Q by using
\begin{align}
Q=\frac{1}{2}m\int v^2 \left( \frac{\partial f_\alpha}{\partial t} \right)_{coll} d^3v- \textbf{R}\cdot \textbf{V}.
\end{align}

If this analysis is done for both the electron and ion VFP equations the result is a set of six transport equations, three each for the electrons and ions.
\begin{gather}
\frac{\partial n_e}{\partial t}+\nabla \cdot (n_e \textbf{V}_e)=0, \\
m_e n_e\frac{\partial \textbf{V}_e}{\partial t} + m_en_e \textbf{V}_e\cdot\nabla \textbf{V}_e +en_e(\textbf{E}+\textbf{V}_e\times\textbf{B})=-\nabla p_e+\textbf{R}_e,\\
\frac{3}{2}n_e\frac{\partial T_e}{\partial t} + \frac{3}{2}n_e\textbf{V}_e\cdot\nabla T_e +\nabla \cdot \textbf{q}'_e+p_e\nabla \cdot\textbf{V}_e =Q_e,\\
\frac{\partial n_i}{\partial t}+\nabla \cdot (n_i \textbf{V}_i)=0, \\
m_i n_i\frac{\partial \textbf{V}_i}{\partial t} + m_i n_i \textbf{V}_i\cdot\nabla \textbf{V}_i - Zen_i(\textbf{E}+\textbf{V}_i\times\textbf{B})=-\nabla p_i+\textbf{R}_i,\\
\frac{3}{2}n_i\frac{\partial T_i}{\partial t} + \frac{3}{2}n_i\textbf{V}_i\cdot\nabla T_i +\nabla \cdot \textbf{q}'_i+p_i\nabla \cdot\textbf{V}_i =Q_i.
\end{gather}

\subsection*{The Single Fluid Model}

Thusfar the plasma can be seen as two inter-penetrating fluids. Using the fact that the mass of the electron is much lower than that of a proton, it is justifiable to ignore the electron inertia and define a simpler single fluid model with fluid velocity $\textbf{V}$ and density $\rho$.

Since $m_i>>m_e$, the total plasma density is dominated by the ion density,
\begin{equation}
\rho=m_i n_i+m_e n_e \approx m_i n_i.
\end{equation}
Likewise the total momentum then becomes the ion momentum, with the fluid velocity the ion velocity (henceforth the subscript on $\textbf{V}_i$ will be dropped)
\begin{equation}
\rho\textbf{V}=m_i n_i \textbf{V}_i+m_e n_e\textbf{V}_e \approx m_i n_i \textbf{V}_i.
\end{equation}
Quasi-neutrality implies the number density of electrons and ions follows the relationship
\begin{equation}
Zn_i=n_e,
\end{equation}
where Z is the average ionisation of the plasma. If the two continuity equations are summed, the above approximations yield the total continuity equation
\begin{equation}
\frac{\partial \rho}{\partial t}+\nabla \cdot (\rho\textbf{V})=0.
\end{equation}
Considering charge continuity, one can define the charge density, current and relative velocity
\begin{align*}
\rho_c&=e(Zn_i-n_e),\\
\textbf{U}&=\textbf{V}_e-\textbf{V}_i,\\
\textbf{j}&=\rho_c \textbf{V}_i-en_e\textbf{U},
\end{align*}
which means the charge continuity equation is 
\begin{equation}
\frac{\partial \rho_c}{\partial t}+\nabla \cdot \textbf{j}=0.
\end{equation}
Since the plasma is quasi-neutral, $\rho_c << en_e$ and so 
\begin{equation}
\textbf{j}=-en_e \textbf{U},
\end{equation}
which gives the quasi-neutrality condition
\begin{equation}
\nabla\cdot\textbf{j}=0.
\end{equation}

The single fluid momentum equation is found by taking the sum of the fluid momentum equations. This equation can be simplified by first applying quasi-neutrality, which removes the electric field term. Momentum is conserved in collisions, and so the collision terms cancel because they satisfy
\begin{equation}
\textbf{R}_e=-\textbf{R}_i.
\end{equation}
After neglecting electron inertia and defining total pressure $p=p_e+p_i$ and using the definition of the current, the momentum equation is
\begin{equation}
\rho\frac{\partial \textbf{V}}{\partial t} + \rho \textbf{V}\cdot\nabla \textbf{V} =-\nabla p+\textbf{j}\times\textbf{B}.
\end{equation}

\subsection*{The Energy Equation}

To find the appropriate energy equation one must begin with the electron energy equation eq. 2.27 and use the current definition, eq. 2.36, to remove the electron velocity. Then one uses the heat flow in the ion frame
\begin{equation}
\textbf{q}=\textbf{q}'-\frac{5}{2en_e}p_e\textbf{j}.
\end{equation}

To find a total energy equation for the plasma, the cold ion assumption will be employed where $T_i\approx 0$. The cold ion approximation is used throughout this thesis because in laser-plasma regimes the thermal energy is dominated by the electron temperature, and the heat flow dominated by the electron heat flow. While ions are also heated in the presence of shocks [@Drake2006IntroductionPhysics], the simulations presented in this thesis do not enter the shock regime. In this approximation the ion pressure can be ignored $p_i\approx 0$ and the ion energy equation is removed. In this case the total thermal energy of the plasma is held by the electron temperature. The energy equation is then
\begin{equation}
\frac{3}{2}n_e\left(\frac{\partial T_e}{\partial t}+\textbf{V}\cdot\nabla T_e\right)+p\nabla \cdot\textbf{V}+\nabla \cdot \textbf{q}=\textbf{R}_e\cdot\textbf{j}/e n_e.
\end{equation}

\subsection*{Maxwell's Equations}

The evolution of electromagnetic fields in the plasma is determined by Maxwell's equations
\begin{align}
&\nabla \cdot \textbf{E}=\frac{\rho_c}{\epsilon_0}, \\
&\nabla \cdot \textbf{B}=0, \\
&\nabla \times \textbf{E}=-\frac{\partial \textbf{B}}{\partial t}, \\
&\nabla \times \textbf{B}=\mu_0 \textbf{j}+\mu_0\epsilon_0\frac{\partial \textbf{E}}{\partial t}.
\end{align}

As the plasma is quasi-neutral, the charge density on a scale above that of the Debye length will be zero, $\rho_c =0$. The temporal regime of interest in this thesis is that described by \textit{low-frequency} phenomena, where the characteristic timescale is much longer than the plasma period, i.e $\partial_t<<\omega_p$. The displacement field in the Ampere-Maxwell law can be ignored since the timescale of the plasma dynamics is far below the fast electron plasma period ($1/\omega_p$) timescale. This means Maxwell's equations in plasmas become
\begin{align}
&\nabla \cdot \textbf{B}=0, \\
&\nabla \times \textbf{E}=-\frac{\partial \textbf{B}}{\partial t}, \\
&\nabla \times \textbf{B}=\mu_0 \textbf{j}.
\end{align}
